#!/bin/bash
# build.sh - Creates config.js from environment variables on Render

echo "🔧 Running build script..."

# Create config.js file with environment variables
cat > config.js << EOF
// ==================== K.R.O Media Configuration ====================
// This file is AUTOMATICALLY GENERATED on Render
// DO NOT EDIT - changes will be overwritten

window.KRO_CONFIG = {
    GOOGLE_SHEETS_API_URL: '${GOOGLE_SHEETS_API_URL}',
    YOUTUBE_CREATORS_API_URL: '${YOUTUBE_CREATORS_API_URL}',
    TOP_STAFF_API_URL: '${TOP_STAFF_API_URL}',
    HERO_IMAGE_API_URL: '${HERO_IMAGE_API_URL}',
    PIN_API_URL: '${PIN_API_URL}',
    ADMIN_API_URL: '${ADMIN_API_URL}',
    IMGBB_API_KEY: '${IMGBB_API_KEY}'
};

console.log('✅ K.R.O Config loaded from Render environment');
EOF

echo "✅ config.js generated successfully!"
echo "📁 File contents:"
cat config.js